name = input("what is your name?")
print("Hello", name)
name = input("What is your name?")
city = input("From which city do you live  in?")
print("Hello", name)
print("you live in", city)
name = input("What is your name?")
age = input("How old are you?")
career = input("What career do you want?")
print("Hello", name)
print("Age", age)
print("Dream career", career)
age = input("How old are you?")
print(type(age))
name = input("What is your real name?")
university = input("Which university were you in?")
degree = input("Which degree were you doing?")
programming = input("What is your favourite programming language?")
job = input("Your dream job?")
print("Hellow", name)
print("Previous university", university)
print("degree of", degree)
print("Favourite programming language", programming)
print("Your dream job", job)
name = input("What is your name?")
university = input("Your previous university?")
degree = input("Degree you were doing?")
programming = input("Your favorite programming language?")
job = input("Your dream job?")
print("------------MY PROFILE---------------")
print("Name:",name)
print("University:", university)
print("Degree:", degree)
print("Favorite programming language:", programming)
print("Dream job:", job)
print("--------------------------------------")